name: thesis
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=11.7
  - pip:
      - black
      - tensorboardX
      - opencv-python
      - torch-tb-profiler
      - nvidia-pyindex
      - nvidia-dali-cuda110
      - cupy-cuda110
      - seaborn